
export const STATES_LIST = [
    { id: 1, title: 'California', value: 'CA' },
    { id: 2, title: 'Florida', value: 'FL' },
    { id: 3, title: 'Georgia', value: 'GA' },
    { id: 4, title: 'Illinois', value: 'IL' },
    { id: 5, title: 'Massachusetts', value: 'MA' },
    { id: 6, title: 'Maryland', value: 'MD' },
    { id: 7, title: 'Missouri', value: 'MO' },
    { id: 8, title: 'Pennsylvania', value: 'PA' },
    { id: 9, title: 'Texas', value: 'TX' },
    { id: 10, title: 'Virginia', value: 'VA' },
    { id: 11, title: 'North Carolina', value: 'NC' },
]

export const STATES = {
    CA: [
        { id: 'CA1', title: 'Sacramento', value: 'sacramento' },
        { id: 'CA2', title: 'San Jose', value: 'san_jose' },
    ],
    FL: [
        { id: 'FL1', title: 'Jacksonville', value: 'jacksonville' },
        { id: 'FL2', title: 'Miami', value: 'miami' },
        { id: 'FL3', title: 'Orlando', value: 'orlando' },
        { id: 'FL4', title: 'Tampa', value: 'tampa' },
    ],
    GA: [
        { id: 'GA1', title: 'Atlanta', value: 'atlanta' },
    ],
    IL: [
        { id: 'IL1', title: 'Chicago', value: 'chicago' },
    ],
    MA: [
        { id: 'MA1', title: 'Boston', value: 'boston' },
    ],
    MD: [
        { id: 'MD1', title: 'Baltimore', value: 'baltimore' },
    ],
    MO: [
        { id: 'MO1', title: 'St. Louis', value: 'st_louis' },
    ],
    PA: [
        { id: 'PA1', title: 'Philadelphia', value: 'philadelphia' },
        { id: 'PA2', title: 'Pittsburgh', value: 'pittsburgh' },
    ],
    TX: [
        { id: 'TX1', title: 'Austin', value: 'austin' },
        { id: 'TX2', title: 'Dallas', value: 'dallas' },
        { id: 'TX3', title: 'Fort Worth', value: 'fort_worth' },
        { id: 'TX4', title: 'Fulshear', value: 'fulshear' },
        { id: 'TX5', title: 'Houston', value: 'houston' },
        { id: 'TX6', title: 'McKinney', value: 'mckinney' },
        { id: 'TX7', title: 'Pearland', value: 'pearland' },
        { id: 'TX8', title: 'San Antonio', value: 'san_antonio' },
        { id: 'TX9', title: 'Spring', value: 'spring' },
        { id: 'TX10', title: 'Tomball', value: 'tomball' },
        { id: 'TX11', title: 'Sugar Land', value: 'sugar_land' },
        { id: 'TX12', title: 'Katy', value: 'katy' },
        { id: 'TX13', title: 'Conroe', value: 'conroe' },
        { id: 'TX14', title: 'Cypress', value: 'cypress' },
        { id: 'TX15', title: 'Richmond', value: 'richmond' },
        { id: 'TX16', title: 'Irving', value: 'irving' },
    ],
    VA: [
        { id: 'VA1', title: 'Alexandria', value: 'alexandria' },
        { id: 'VA2', title: 'Richmond', value: 'richmond' },
    ],
    NC: [
        { id: 'NC1', title: 'Charlotte', value: 'charlotte' },
    ],
}


export const CITIES = {
    ca_sacramento: {
        id: 'CA1',
        title: 'Sacramento',
        value: 'sacramento',
        address: '3631 Truxel Road #1193 Sacramento, CA 95834',
        phone: '(279) 300-3915',
        days: 'Monday - Saturday',
        hours: '07:00 am - 08:00 pm',
    },
    ca_san_jose: {
        id: 'CA2',
        title: 'San Jose',
        value: 'san_jose',
        address: '',
        phone: '',
        days: 'Monday - Saturday',
        hours: '07:00 am - 08:00 pm',
    },
    fl_jacksonville: {
        id: 'FL1',
        title: 'Jacksonville',
        value: 'jacksonville',
        address: '',
        phone: '',
        days: 'Monday - Saturday',
        hours: '07:00 am - 08:00 pm',
    },
    fl_miami: {
        id: 'FL2',
        title: 'Miami',
        value: 'miami',
        address: '',
        phone: '',
        days: 'Monday - Saturday',
        hours: '07:00 am - 08:00 pm',
    },
    fl_orlando: {
        id: 'FL3',
        title: 'Orlando',
        value: 'orlando',
        address: '',
        phone: '',
        days: 'Monday - Saturday',
        hours: '07:00 am - 08:00 pm',
    },
    fl_tampa: {
        id: 'FL4',
        title: 'Tampa',
        value: 'tampa',
        address: '',
        phone: '',
        days: 'Monday - Saturday',
        hours: '07:00 am - 08:00 pm',
    },
    ga_atlanta: {
        id: 'GA1',
        title: 'Atlanta',
        value: 'atlanta',
        address: '',
        phone: '',
        days: 'Monday - Saturday',
        hours: '07:00 am - 08:00 pm',
    },
    il_chicago: {
        id: 'IL1',
        title: 'Chicago',
        value: 'chicago',
        address: '',
        phone: '',
        days: 'Monday - Saturday',
        hours: '07:00 am - 08:00 pm',
    },
    ma_boston: {
        id: 'MA1',
        title: 'Boston',
        value: 'boston',
        address: '',
        phone: '',
        days: 'Monday - Saturday',
        hours: '07:00 am - 08:00 pm',
    },
    md_baltimore: {
        id: 'MD1',
        title: 'Baltimore',
        value: 'baltimore',
        address: '',
        phone: '',
        days: 'Monday - Saturday',
        hours: '07:00 am - 08:00 pm',
    },
    mo_st_louis: {
        id: 'MO1',
        title: 'St. Louis',
        value: 'st_louis',
        address: '',
        phone: '',
        days: 'Monday - Saturday',
        hours: '07:00 am - 08:00 pm',
    },
    pa_philadelphia: {
        id: 'PA1',
        title: 'Philadelphia',
        value: 'philadelphia',
        address: '',
        phone: '',
        days: 'Monday - Saturday',
        hours: '07:00 am - 08:00 pm',
    },
    pa_pittsburgh: {
        id: 'PA2',
        title: 'Pittsburgh',
        value: 'pittsburgh',
        address: '',
        phone: '',
        days: 'Monday - Saturday',
        hours: '07:00 am - 08:00 pm',
    },
    tx_austin: {
        id: 'TX1',
        title: 'Austin',
        value: 'austin',
        address: '',
        phone: '',
        days: 'Monday - Saturday',
        hours: '07:00 am - 08:00 pm',
    },
    tx_dallas: {
        id: 'TX2',
        title: 'Dallas',
        value: 'dallas',
        address: '',
        phone: '',
        days: 'Monday - Saturday',
        hours: '07:00 am - 08:00 pm',
    },
    tx_fort_worth: {
        id: 'TX3',
        title: 'Fort Worth',
        value: 'fort_worth',
        address: '',
        phone: '',
        days: 'Monday - Saturday',
        hours: '07:00 am - 08:00 pm',
    },
    tx_fulshear: {
        id: 'TX4',
        title: 'Fulshear',
        value: 'fulshear',
        address: '',
        phone: '',
        days: 'Monday - Saturday',
        hours: '07:00 am - 08:00 pm',
    },
    tx_houston: {
        id: 'TX5',
        title: 'Houston',
        value: 'houston',
        address: '',
        phone: '',
        days: 'Monday - Saturday',
        hours: '07:00 am - 08:00 pm',
    },
    tx_mckinney: {
        id: 'TX6',
        title: 'McKinney',
        value: 'mckinney',
        address: '',
        phone: '',
        days: 'Monday - Saturday',
        hours: '07:00 am - 08:00 pm',
    },
    tx_pearland: {
        id: 'TX7',
        title: 'Pearland',
        value: 'pearland',
        address: '',
        phone: '',
        days: 'Monday - Saturday',
        hours: '07:00 am - 08:00 pm',
    },
    tx_san_antonio: {
        id: 'TX8',
        title: 'San Antonio',
        value: 'san_antonio',
        address: '',
        phone: '',
        days: 'Monday - Saturday',
        hours: '07:00 am - 08:00 pm',
    },
    tx_spring: {
        id: 'TX9',
        title: 'Spring',
        value: 'spring',
        address: '',
        phone: '',
        days: 'Monday - Saturday',
        hours: '07:00 am - 08:00 pm',
    },
    tx_tomball: {
        id: 'TX10',
        title: 'Tomball',
        value: 'tomball',
        address: '',
        phone: '',
        days: 'Monday - Saturday',
        hours: '07:00 am - 08:00 pm',
    },
    tx_sugar_land: {
        id: 'TX11',
        title: 'Sugar Land',
        value: 'sugar_land',
        address: '',
        phone: '',
        days: 'Monday - Saturday',
        hours: '07:00 am - 08:00 pm',
    },
    tx_katy: {
        id: 'TX12',
        title: 'Katy',
        value: 'katy',
        address: '',
        phone: '',
        days: 'Monday - Saturday',
        hours: '07:00 am - 08:00 pm',
    },
    tx_conroe: {
        id: 'TX13',
        title: 'Conroe',
        value: 'conroe',
        address: '',
        phone: '',
        days: 'Monday - Saturday',
        hours: '07:00 am - 08:00 pm',
    },
    tx_cypress: {
        id: 'TX14',
        title: 'Cypress',
        value: 'cypress',
        address: '',
        phone: '',
        days: 'Monday - Saturday',
        hours: '07:00 am - 08:00 pm',
    },
    tx_richmond: {
        id: 'TX15',
        title: 'Richmond',
        value: 'richmond',
        address: '',
        phone: '',
        days: 'Monday - Saturday',
        hours: '07:00 am - 08:00 pm',
    },
    tx_irving: {
        id: 'TX16',
        title: 'Irving',
        value: 'irving',
        address: '',
        phone: '',
        days: 'Monday - Saturday',
        hours: '07:00 am - 08:00 pm',
    },
    va_alexandria: {
        id: 'VA1',
        title: 'Alexandria',
        value: 'alexandria',
        address: '',
        phone: '',
        days: 'Monday - Saturday',
        hours: '07:00 am - 08:00 pm',
    },
    va_richmond: {
        id: 'VA2',
        title: 'Richmond',
        value: 'richmond',
        address: '',
        phone: '',
        days: 'Monday - Saturday',
        hours: '07:00 am - 08:00 pm',
    },
    nc_charlotte: {
        id: 'NC1',
        title: 'Charlotte',
        value: 'charlotte',
        address: '',
        phone: '',
        days: 'Monday - Saturday',
        hours: '07:00 am - 08:00 pm',
    },
}
