
export const STATES_LIST = [
    { id: 1, title: 'California', value: 'CA' },
    { id: 2, title: 'Florida', value: 'FL' },
    { id: 3, title: 'Georgia', value: 'GA' },
    { id: 4, title: 'Illinois', value: 'IL' },
    { id: 5, title: 'Massachusetts', value: 'MA' },
    { id: 6, title: 'Maryland', value: 'MD' },
    { id: 7, title: 'Missouri', value: 'MO' },
    { id: 8, title: 'Pennsylvania', value: 'PA' },
    { id: 9, title: 'Texas', value: 'TX' },
    { id: 10, title: 'Virginia', value: 'VA' },
    { id: 11, title: 'North Carolina', value: 'NC' },
    { id: 12, title: 'New Jersey', value: 'NJ' },
]

export const STATES = {
    CA: [
        { id: 'CA1', state: 'California', title: 'Sacramento', value: 'sacramento' },
        { id: 'CA2', state: 'California', title: 'San Jose', value: 'san_jose' },
    ],
    FL: [
        { id: 'FL1', state: 'Florida', title: 'Jacksonville', value: 'jacksonville' },
        { id: 'FL2', state: 'Florida', title: 'Miami', value: 'miami' },
        { id: 'FL3', state: 'Florida', title: 'Orlando', value: 'orlando' },
        { id: 'FL4', state: 'Florida', title: 'Tampa', value: 'tampa' },
    ],
    GA: [
        { id: 'GA1', state: 'Georgia', title: 'Atlanta', value: 'atlanta' },
    ],
    IL: [
        { id: 'IL1', state: 'Illinois', title: 'Chicago', value: 'chicago' },
    ],
    MA: [
        { id: 'MA1', state: 'Massachusetts', title: 'Boston', value: 'boston' },
    ],
    MD: [
        { id: 'MD1', state: 'Maryland', title: 'Baltimore', value: 'baltimore' },
    ],
    MO: [
        { id: 'MO1', state: 'Missouri', title: 'St. Louis', value: 'st_louis' },
    ],
    PA: [
        { id: 'PA1', state: 'Pennsylvania', title: 'Philadelphia', value: 'philadelphia' },
        { id: 'PA2', state: 'Pennsylvania', title: 'Pittsburgh', value: 'pittsburgh' },
    ],
    TX: [
        { id: 'TX1', state: 'Texas', title: 'Austin', value: 'austin' },
        { id: 'TX2', state: 'Texas', title: 'Dallas', value: 'dallas' },
        { id: 'TX3', state: 'Texas', title: 'Fort Worth', value: 'fort_worth' },
        { id: 'TX4', state: 'Texas', title: 'Fulshear', value: 'fulshear' },
        { id: 'TX5', state: 'Texas', title: 'Houston', value: 'houston' },
        { id: 'TX6', state: 'Texas', title: 'McKinney', value: 'mckinney' },
        { id: 'TX7', state: 'Texas', title: 'Pearland', value: 'pearland' },
        { id: 'TX8', state: 'Texas', title: 'San Antonio', value: 'san_antonio' },
        { id: 'TX9', state: 'Texas', title: 'Spring', value: 'spring' },
        { id: 'TX10', state: 'Texas', title: 'Tomball', value: 'tomball' },
        { id: 'TX11', state: 'Texas', title: 'Sugar Land', value: 'sugar_land' },
        { id: 'TX12', state: 'Texas', title: 'Katy', value: 'katy' },
        { id: 'TX13', state: 'Texas', title: 'Conroe', value: 'conroe' },
        { id: 'TX14', state: 'Texas', title: 'Cypress', value: 'cypress' },
        { id: 'TX15', state: 'Texas', title: 'Richmond', value: 'richmond' },
        { id: 'TX16', state: 'Texas', title: 'Irving', value: 'irving' },
    ],
    VA: [
        { id: 'VA1', state: 'Virginia', title: 'Alexandria', value: 'alexandria' },
        { id: 'VA2', state: 'Virginia', title: 'Richmond', value: 'richmond' },
    ],
    NC: [
        { id: 'NC1', state: 'North Carolina', title: 'Charlotte', value: 'charlotte' },
    ],
    NJ: [
        { id: 'NJ1', state: 'New Jersey', title: 'Livingston', value: 'livingston' },
    ],
}


export const CITIES = {
    ca_sacramento: {
        id: 'CA1',
        stateShort: 'CA',
        state: 'California',
        title: 'Sacramento',
        value: 'sacramento',
        abbreviation: 'sacramento-ca',
        address: '3631 Truxel Road #1193 Sacramento, CA 95834',
        phone: '(279) 300-3915',
        days: 'Monday - Saturday',
        hours: '07:00 am - 08:00 pm',
        carUrl: '/img/cars/ca_sacramento_car.webp',
        mapUrl: '/img/maps/ca_sacramento_map.webp',
        employees: [
            { id: 1, name: 'Aydin', image: '/img/employees/employee1.webp' },
            { id: 2, name: 'Oreck', image: '/img/employees/employee2.webp' },
            { id: 3, name: 'Farr', image: '/img/employees/employee3.webp' },
        ]
    },
    ca_san_jose: {
        id: 'CA2',
        stateShort: 'CA',
        state: 'California',
        title: 'San Jose',
        value: 'san_jose',
        abbreviation: 'san-jose-ca',
        address: '760 Newhall Drive #1164 San Jose, CA 95110',
        phone: '(408) 239-4881',
        days: 'Monday - Saturday',
        hours: '07:00 am - 08:00 pm',
        carUrl: '/img/cars/ca_san_jose_car.webp',
        mapUrl: '/img/maps/ca_san_jose_map.webp',
        employees: [
            { id: 1, name: 'Aydin', image: '/img/employees/employee1.webp' },
            { id: 2, name: 'Oreck', image: '/img/employees/employee2.webp' },
            { id: 3, name: 'Farr', image: '/img/employees/employee3.webp' },
        ]
    },
    fl_jacksonville: {
        id: 'FL1',
        stateShort: 'FL',
        state: 'Florida',
        title: 'Jacksonville',
        value: 'jacksonville',
        abbreviation: 'jacksonville-fl',
        address: '2695 Post St #1177 Jacksonville, FL 32204',
        phone: '(904) 565-5638',
        days: 'Monday - Saturday',
        hours: '07:00 am - 08:00 pm',
        carUrl: '/img/cars/fl_jacksonville_car.webp',
        mapUrl: '/img/maps/fl_jacksonville_map.webp',
        employees: [
            { id: 1, name: 'Aydin', image: '/img/employees/employee1.webp' },
            { id: 2, name: 'Oreck', image: '/img/employees/employee2.webp' },
            { id: 3, name: 'Farr', image: '/img/employees/employee3.webp' },
        ]
    },
    fl_miami: {
        id: 'FL2',
        stateShort: 'FL',
        state: 'Florida',
        title: 'Miami',
        value: 'miami',
        abbreviation: 'miami-fl',
        address: '1065 SW 8th St #2078 Miami, FL 33130',
        phone: '(305) 547-8157',
        days: 'Monday - Saturday',
        hours: '07:00 am - 08:00 pm',
        carUrl: '/img/cars/fl_miami_car.webp',
        mapUrl: '/img/maps/fl_miami_map.webp',
        employees: [
            { id: 1, name: 'Aydin', image: '/img/employees/employee1.webp' },
            { id: 2, name: 'Oreck', image: '/img/employees/employee2.webp' },
            { id: 3, name: 'Farr', image: '/img/employees/employee3.webp' },
        ]
    },
    fl_orlando: {
        id: 'FL3',
        stateShort: 'FL',
        state: 'Florida',
        title: 'Orlando',
        value: 'orlando',
        abbreviation: 'orlando-fl',
        address: '4530 S. Orange Blossom Trail #790 Orlando, FL 32839',
        phone: '(689) 267-3141',
        days: 'Monday - Saturday',
        hours: '07:00 am - 08:00 pm',
        carUrl: '/img/cars/fl_orlando_car.webp',
        mapUrl: '/img/maps/fl_orlando_map.webp',
        employees: [
            { id: 1, name: 'Aydin', image: '/img/employees/employee1.webp' },
            { id: 2, name: 'Oreck', image: '/img/employees/employee2.webp' },
            { id: 3, name: 'Farr', image: '/img/employees/employee3.webp' },
        ]
    },
    fl_tampa: {
        id: 'FL4',
        stateShort: 'FL',
        state: 'Florida',
        title: 'Tampa',
        value: 'tampa',
        abbreviation: 'tampa-fl',
        address: '7901 4th St N #300, St Petersburg 33702',
        phone: '(813) 400-1003',
        days: 'Monday - Saturday',
        hours: '07:00 am - 08:00 pm',
        carUrl: '/img/cars/fl_tampa_car.webp',
        mapUrl: '/img/maps/fl_tampa_map.webp',
        employees: [
            { id: 1, name: 'Aydin', image: '/img/employees/employee1.webp' },
            { id: 2, name: 'Oreck', image: '/img/employees/employee2.webp' },
            { id: 3, name: 'Farr', image: '/img/employees/employee3.webp' },
        ]
    },
    ga_atlanta: {
        id: 'GA1',
        stateShort: 'GA',
        state: 'Georgia',
        title: 'Atlanta',
        value: 'atlanta',
        abbreviation: 'atlanta-ga',
        address: '1954 Airport Road # 1384 Atlanta, GA 30341',
        phone: '(470) 749-8889',
        days: 'Monday - Saturday',
        hours: '07:00 am - 08:00 pm',
        carUrl: '/img/cars/ga_atlanta_car.webp',
        mapUrl: '/img/maps/ga_atlanta_map.webp',
        employees: [
            { id: 1, name: 'Aydin', image: '/img/employees/employee1.webp' },
            { id: 2, name: 'Oreck', image: '/img/employees/employee2.webp' },
            { id: 3, name: 'Farr', image: '/img/employees/employee3.webp' },
        ]
    },
    il_chicago: {
        id: 'IL1',
        stateShort: 'IL',
        state: 'Illinois',
        title: 'Chicago',
        value: 'chicago',
        abbreviation: 'chicago-il',
        address: '1509 Waukegan Rd #1169, Glenview, IL 60025',
        phone: '(224) 998-0811',
        days: 'Monday - Saturday',
        hours: '07:00 am - 08:00 pm',
        carUrl: '/img/cars/il_chicago_car.webp',
        mapUrl: '/img/maps/il_chicago_map.webp',
        employees: [
            { id: 1, name: 'Aydin', image: '/img/employees/employee1.webp' },
            { id: 2, name: 'Oreck', image: '/img/employees/employee2.webp' },
            { id: 3, name: 'Farr', image: '/img/employees/employee3.webp' },
        ]
    },
    ma_boston: {
        id: 'MA1',
        stateShort: 'MA',
        state: 'Massachusetts',
        title: 'Boston',
        value: 'boston',
        abbreviation: 'boston-ma',
        address: '160 Alewife Brook Pkwy #1328 Cambridge, MA 02138',
        phone: '(857) 353-6048',
        days: 'Monday - Saturday',
        hours: '07:00 am - 08:00 pm',
        carUrl: '/img/cars/ma_boston_car.webp',
        mapUrl: '/img/maps/ma_boston_map.webp',
        employees: [
            { id: 1, name: 'Aydin', image: '/img/employees/employee1.webp' },
            { id: 2, name: 'Oreck', image: '/img/employees/employee2.webp' },
            { id: 3, name: 'Farr', image: '/img/employees/employee3.webp' },
        ]
    },
    md_baltimore: {
        id: 'MD1',
        stateShort: 'MD',
        state: 'Maryland',
        title: 'Baltimore',
        value: 'baltimore',
        abbreviation: 'baltimore-md',
        address: '822 Guilford Avenue #2029 Baltimore, MD 21202',
        phone: '(410) 753-2277',
        days: 'Monday - Saturday',
        hours: '07:00 am - 08:00 pm',
        carUrl: '/img/cars/md_baltimore_car.webp',
        mapUrl: '/img/maps/md_baltimore_map.webp',
        employees: [
            { id: 1, name: 'Aydin', image: '/img/employees/employee1.webp' },
            { id: 2, name: 'Oreck', image: '/img/employees/employee2.webp' },
            { id: 3, name: 'Farr', image: '/img/employees/employee3.webp' },
        ]
    },
    mo_st_louis: {
        id: 'MO1',
        stateShort: 'MO',
        state: 'Missouri',
        title: 'St. Louis',
        value: 'st_louis',
        abbreviation: 'st-louis-mo',
        address: '6907 Page Ave #1264 St Louis, MO 63133',
        phone: '(314) 219-1443',
        days: 'Monday - Saturday',
        hours: '07:00 am - 08:00 pm',
        carUrl: '/img/cars/mo_st_louis_car.webp',
        mapUrl: '/img/maps/mo_st_louis_map.webp',
        employees: [
            { id: 1, name: 'Aydin', image: '/img/employees/employee1.webp' },
            { id: 2, name: 'Oreck', image: '/img/employees/employee2.webp' },
            { id: 3, name: 'Farr', image: '/img/employees/employee3.webp' },
        ]
    },
    pa_philadelphia: {
        id: 'PA1',
        stateShort: 'PA',
        state: 'Pennsylvania',
        title: 'Philadelphia',
        value: 'philadelphia',
        abbreviation: 'philadelphia-pa',
        address: '7244 Castor Ave #1449 Philadelphia, PA 19149',
        phone: '(267) 888-2078',
        days: 'Monday - Saturday',
        hours: '07:00 am - 08:00 pm',
        carUrl: '/img/cars/pa_philadelphia_car.webp',
        mapUrl: '/img/maps/pa_philadelphia_map.webp',
        employees: [
            { id: 1, name: 'Aydin', image: '/img/employees/employee1.webp' },
            { id: 2, name: 'Oreck', image: '/img/employees/employee2.webp' },
            { id: 3, name: 'Farr', image: '/img/employees/employee3.webp' },
        ]
    },
    pa_pittsburgh: {
        id: 'PA2',
        stateShort: 'PA',
        state: 'Pennsylvania',
        title: 'Pittsburgh',
        value: 'pittsburgh',
        abbreviation: 'pittsburgh-pa',
        address: '2515 Banksville Road #1049 Pittsburgh, PA 15216',
        phone: '(412) 420-6315',
        days: 'Monday - Saturday',
        hours: '07:00 am - 08:00 pm',
        carUrl: '/img/cars/pa_pittsburgh_car.webp',
        mapUrl: '/img/maps/pa_pittsburgh_map.webp',
        employees: [
            { id: 1, name: 'Aydin', image: '/img/employees/employee1.webp' },
            { id: 2, name: 'Oreck', image: '/img/employees/employee2.webp' },
            { id: 3, name: 'Farr', image: '/img/employees/employee3.webp' },
        ]
    },
    tx_austin: {
        id: 'TX1',
        stateShort: 'TX',
        state: 'Texas',
        title: 'Austin',
        value: 'austin',
        abbreviation: 'austin-tx',
        address: '13359 N Hwy 183 #406-643, Austin, TX 78750',
        phone: '(737) 241-0883',
        days: 'Monday - Saturday',
        hours: '07:00 am - 08:00 pm',
        carUrl: '/img/cars/tx_austin_car.webp',
        mapUrl: '/img/maps/tx_austin_map.webp',
        employees: [
            { id: 1, name: 'Aydin', image: '/img/employees/employee1.webp' },
            { id: 2, name: 'Oreck', image: '/img/employees/employee2.webp' },
            { id: 3, name: 'Farr', image: '/img/employees/employee3.webp' },
        ]
    },
    tx_dallas: {
        id: 'TX2',
        stateShort: 'TX',
        state: 'Texas',
        title: 'Dallas',
        value: 'dallas',
        abbreviation: 'dallas-tx',
        address: '16817 Coit Rd #2304, Dallas, TX 75248',
        phone: '(972) 666-0299',
        days: 'Monday - Saturday',
        hours: '07:00 am - 08:00 pm',
        carUrl: '/img/cars/tx_dallas_car.webp',
        mapUrl: '/img/maps/tx_dallas_map.webp',
        employees: [
            { id: 1, name: 'Aydin', image: '/img/employees/employee1.webp' },
            { id: 2, name: 'Oreck', image: '/img/employees/employee2.webp' },
            { id: 3, name: 'Farr', image: '/img/employees/employee3.webp' },
        ]
    },
    tx_fort_worth: {
        id: 'TX3',
        stateShort: 'TX',
        state: 'Texas',
        title: 'Fort Worth',
        value: 'fort_worth',
        abbreviation: 'fort-worth-tx',
        address: '6313 Lake Worth Blvd. #1021 Lake Worth, TX 76135',
        phone: '(817) 200-7005',
        days: 'Monday - Saturday',
        hours: '07:00 am - 08:00 pm',
        carUrl: '/img/cars/tx_fort_worth_car.webp',
        mapUrl: '/img/maps/tx_fort_worth_map.webp',
        employees: [
            { id: 1, name: 'Aydin', image: '/img/employees/employee1.webp' },
            { id: 2, name: 'Oreck', image: '/img/employees/employee2.webp' },
            { id: 3, name: 'Farr', image: '/img/employees/employee3.webp' },
        ]
    },
    tx_fulshear: {
        id: 'TX4',
        stateShort: 'TX',
        state: 'Texas',
        title: 'Fulshear',
        value: 'fulshear',
        abbreviation: 'fulshear-tx',
        address: '31602 Roldan Ln, Fulshear, TX 77441',
        phone: '(713) 770-6055',
        days: 'Monday - Saturday',
        hours: '07:00 am - 08:00 pm',
        carUrl: '/img/cars/tx_fulshear_car.webp',
        mapUrl: '/img/maps/tx_fulshear_map.webp',
        employees: [
            { id: 1, name: 'Aydin', image: '/img/employees/employee1.webp' },
            { id: 2, name: 'Oreck', image: '/img/employees/employee2.webp' },
            { id: 3, name: 'Farr', image: '/img/employees/employee3.webp' },
        ]
    },
    tx_houston: {
        id: 'TX5',
        stateShort: 'TX',
        state: 'Texas',
        title: 'Houston',
        value: 'houston',
        abbreviation: 'houston-tx',
        address: '2742 Jeanetta St #722, Houston, TX 77063',
        phone: '(832) 998-0886',
        days: 'Monday - Saturday',
        hours: '07:00 am - 08:00 pm',
        carUrl: '/img/cars/tx_houston_car.webp',
        mapUrl: '/img/maps/tx_houston_map.webp',
        employees: [
            { id: 1, name: 'Aydin', image: '/img/employees/employee1.webp' },
            { id: 2, name: 'Oreck', image: '/img/employees/employee2.webp' },
            { id: 3, name: 'Farr', image: '/img/employees/employee3.webp' },
        ]
    },
    tx_mckinney: {
        id: 'TX6',
        stateShort: 'TX',
        state: 'Texas',
        title: 'McKinney',
        value: 'mckinney',
        abbreviation: 'mckinney-tx',
        address: '5900 South Lake Forest, #300 McKinney, TX 75070',
        phone: '(469) 718-2442',
        days: 'Monday - Saturday',
        hours: '07:00 am - 08:00 pm',
        carUrl: '/img/cars/tx_mckinney_car.webp',
        mapUrl: '/img/maps/tx_mckinney_map.webp',
        employees: [
            { id: 1, name: 'Aydin', image: '/img/employees/employee1.webp' },
            { id: 2, name: 'Oreck', image: '/img/employees/employee2.webp' },
            { id: 3, name: 'Farr', image: '/img/employees/employee3.webp' },
        ]
    },
    tx_pearland: {
        id: 'TX7',
        stateShort: 'TX',
        state: 'Texas',
        title: 'Pearland',
        value: 'pearland',
        abbreviation: 'pearland-tx',
        address: '1853 Pearland Pkwy Ste 123 Pearland, TX 77581',
        phone: '(346) 547-4511',
        days: 'Monday - Saturday',
        hours: '07:00 am - 08:00 pm',
        carUrl: '/img/cars/tx_pearland_car.webp',
        mapUrl: '/img/maps/tx_pearland_map.webp',
        employees: [
            { id: 1, name: 'Aydin', image: '/img/employees/employee1.webp' },
            { id: 2, name: 'Oreck', image: '/img/employees/employee2.webp' },
            { id: 3, name: 'Farr', image: '/img/employees/employee3.webp' },
        ]
    },
    tx_san_antonio: {
        id: 'TX8',
        stateShort: 'TX',
        state: 'Texas',
        title: 'San Antonio',
        value: 'san_antonio',
        abbreviation: 'san-antonio-tx',
        address: '13423 Blanco Road #687, San Antonio, TX 78216',
        phone: '(726) 216-7575',
        days: 'Monday - Saturday',
        hours: '07:00 am - 08:00 pm',
        carUrl: '/img/cars/tx_san_antonio_car.webp',
        mapUrl: '/img/maps/tx_san_antonio_map.webp',
        employees: [
            { id: 1, name: 'Aydin', image: '/img/employees/employee1.webp' },
            { id: 2, name: 'Oreck', image: '/img/employees/employee2.webp' },
            { id: 3, name: 'Farr', image: '/img/employees/employee3.webp' },
        ]
    },
    tx_spring: {
        id: 'TX9',
        stateShort: 'TX',
        state: 'Texas',
        title: 'Spring',
        value: 'spring',
        abbreviation: 'spring-tx',
        address: '22742 Cypresswood Drive #1154 Spring, TX 77373',
        phone: '(346) 290-7544',
        days: 'Monday - Saturday',
        hours: '07:00 am - 08:00 pm',
        carUrl: '/img/cars/tx_spring_car.webp',
        mapUrl: '/img/maps/tx_spring_map.webp',
        employees: [
            { id: 1, name: 'Aydin', image: '/img/employees/employee1.webp' },
            { id: 2, name: 'Oreck', image: '/img/employees/employee2.webp' },
            { id: 3, name: 'Farr', image: '/img/employees/employee3.webp' },
        ]
    },
    tx_tomball: {
        id: 'TX10',
        stateShort: 'TX',
        state: 'Texas',
        title: 'Tomball',
        value: 'tomball',
        abbreviation: 'tomball-tx',
        address: '27708 Tomball Parkway Tomball, TX 77375',
        phone: '(832) 665-2998',
        days: 'Monday - Saturday',
        hours: '07:00 am - 08:00 pm',
        carUrl: '/img/cars/tx_tomball_car.webp',
        mapUrl: '/img/maps/tx_tomball_map.webp',
        employees: [
            { id: 1, name: 'Aydin', image: '/img/employees/employee1.webp' },
            { id: 2, name: 'Oreck', image: '/img/employees/employee2.webp' },
            { id: 3, name: 'Farr', image: '/img/employees/employee3.webp' },
        ]
    },
    tx_sugar_land: {
        id: 'TX11',
        stateShort: 'TX',
        state: 'Texas',
        title: 'Sugar Land',
        value: 'sugar_land',
        abbreviation: 'sugar-land-tx',
        address: '5826 New Territory Boulevard #234, Sugar Land, TX 77479',
        phone: '(832) 665-2955',
        days: 'Monday - Saturday',
        hours: '07:00 am - 08:00 pm',
        carUrl: '/img/cars/tx_sugar_land_car.webp',
        mapUrl: '/img/maps/tx_sugar_land_map.webp',
        employees: [
            { id: 1, name: 'Aydin', image: '/img/employees/employee1.webp' },
            { id: 2, name: 'Oreck', image: '/img/employees/employee2.webp' },
            { id: 3, name: 'Farr', image: '/img/employees/employee3.webp' },
        ]
    },
    tx_katy: {
        id: 'TX12',
        stateShort: 'TX',
        state: 'Texas',
        title: 'Katy',
        value: 'katy',
        abbreviation: 'katy-tx',
        address: '9722 Gaston Rd #150, Katy, TX 77494',
        phone: '(832) 665-2936',
        days: 'Monday - Saturday',
        hours: '07:00 am - 08:00 pm',
        carUrl: '/img/cars/tx_katy_car.webp',
        mapUrl: '/img/maps/tx_katy_map.webp',
        employees: [
            { id: 1, name: 'Aydin', image: '/img/employees/employee1.webp' },
            { id: 2, name: 'Oreck', image: '/img/employees/employee2.webp' },
            { id: 3, name: 'Farr', image: '/img/employees/employee3.webp' },
        ]
    },
    tx_conroe: {
        id: 'TX13',
        stateShort: 'TX',
        state: 'Texas',
        title: 'Conroe',
        value: 'conroe',
        abbreviation: 'conroe-tx',
        address: '2257 N Loop 336 W #140, Conroe, TX 77304',
        phone: '(936) 249-2540',
        days: 'Monday - Saturday',
        hours: '07:00 am - 08:00 pm',
        carUrl: '/img/cars/tx_conroe_car.webp',
        mapUrl: '/img/maps/tx_conroe_map.webp',
        employees: [
            { id: 1, name: 'Aydin', image: '/img/employees/employee1.webp' },
            { id: 2, name: 'Oreck', image: '/img/employees/employee2.webp' },
            { id: 3, name: 'Farr', image: '/img/employees/employee3.webp' },
        ]
    },
    tx_cypress: {
        id: 'TX14',
        stateShort: 'TX',
        state: 'Texas',
        title: 'Cypress',
        value: 'cypress',
        abbreviation: 'cypress-tx',
        address: '12320 Barker Cypress Rd #600, Cypress, TX 77429',
        phone: '(832) 665-2921',
        days: 'Monday - Saturday',
        hours: '07:00 am - 08:00 pm',
        carUrl: '/img/cars/tx_cypress_car.webp',
        mapUrl: '/img/maps/tx_cypress_map.webp',
        employees: [
            { id: 1, name: 'Aydin', image: '/img/employees/employee1.webp' },
            { id: 2, name: 'Oreck', image: '/img/employees/employee2.webp' },
            { id: 3, name: 'Farr', image: '/img/employees/employee3.webp' },
        ]
    },
    tx_richmond: {
        id: 'TX15',
        stateShort: 'TX',
        state: 'Texas',
        title: 'Richmond',
        value: 'richmond',
        abbreviation: 'richmond-tx',
        address: '19714 Lago Terrace Loop, Richmond, TX 77407',
        phone: '(832) 665-2925',
        days: 'Monday - Saturday',
        hours: '07:00 am - 08:00 pm',
        carUrl: '/img/cars/tx_richmond_car.webp',
        mapUrl: '/img/maps/tx_richmond_map.webp',
        employees: [
            { id: 1, name: 'Aydin', image: '/img/employees/employee1.webp' },
            { id: 2, name: 'Oreck', image: '/img/employees/employee2.webp' },
            { id: 3, name: 'Farr', image: '/img/employees/employee3.webp' },
        ]
    },
    tx_irving: {
        id: 'TX16',
        stateShort: 'TX',
        state: 'Texas',
        title: 'Irving',
        value: 'irving',
        abbreviation: 'irving-tx',
        address: '4157 W Northgate Dr #1002, Irving, TX 75062',
        phone: '(469) 613-3397',
        days: 'Monday - Saturday',
        hours: '07:00 am - 08:00 pm',
        carUrl: '/img/cars/tx_irving_car.webp',
        mapUrl: '/img/maps/tx_irving_map.webp',
        employees: [
            { id: 1, name: 'Aydin', image: '/img/employees/employee1.webp' },
            { id: 2, name: 'Oreck', image: '/img/employees/employee2.webp' },
            { id: 3, name: 'Farr', image: '/img/employees/employee3.webp' },
        ]
    },
    va_alexandria: {
        id: 'VA1',
        stateShort: 'VA',
        state: 'Virginia',
        title: 'Alexandria',
        value: 'alexandria',
        abbreviation: 'alexandria-va',
        address: '3301 Richmond Hwy. #1333 Alexandria, VA 22305',
        phone: '(571) 800-0980',
        days: 'Monday - Saturday',
        hours: '07:00 am - 08:00 pm',
        carUrl: '/img/cars/va_alexandria_car.webp',
        mapUrl: '/img/maps/va_alexandria_map.webp',
        employees: [
            { id: 1, name: 'Aydin', image: '/img/employees/employee1.webp' },
            { id: 2, name: 'Oreck', image: '/img/employees/employee2.webp' },
            { id: 3, name: 'Farr', image: '/img/employees/employee3.webp' },
        ]
    },
    va_richmond: {
        id: 'VA2',
        stateShort: 'VA',
        state: 'Virginia',
        title: 'Richmond',
        value: 'richmond',
        abbreviation: 'richmond-va',
        address: '1248 CarMia Way #1081 Richmond, VA 23235',
        phone: '(804) 486-6280',
        days: 'Monday - Saturday',
        hours: '07:00 am - 08:00 pm',
        carUrl: '/img/cars/va_richmond_car.webp',
        mapUrl: '/img/maps/va_richmond_map.webp',
        employees: [
            { id: 1, name: 'Aydin', image: '/img/employees/employee1.webp' },
            { id: 2, name: 'Oreck', image: '/img/employees/employee2.webp' },
            { id: 3, name: 'Farr', image: '/img/employees/employee3.webp' },
        ]
    },
    nc_charlotte: {
        id: 'NC1',
        stateShort: 'NC',
        state: 'North Carolina',
        title: 'Charlotte',
        value: 'charlotte',
        abbreviation: 'charlotte-nc',
        address: '1235 East Blvd #3923 Charlotte, NC 28203',
        phone: '(980) 301-9636',
        days: 'Monday - Saturday',
        hours: '07:00 am - 08:00 pm',
        carUrl: '/img/cars/nc_charlotte_car.webp',
        mapUrl: '/img/maps/nc_charlotte_map.webp',
        employees: [
            { id: 1, name: 'Aydin', image: '/img/employees/employee1.webp' },
            { id: 2, name: 'Oreck', image: '/img/employees/employee2.webp' },
            { id: 3, name: 'Farr', image: '/img/employees/employee3.webp' },
        ]
    },
    nj_livingston: {
        id: 'NJ1',
        stateShort: 'NJ',
        state: 'North Carolina',
        title: 'Livingston',
        value: 'livingston',
        abbreviation: 'livingston-nj',
        address: '506 W. Mt. Pleasant Ave #3433 Livingston, NJ 07039',
        phone: '(862) 343-5590',
        days: 'Monday - Saturday',
        hours: '07:00 am - 08:00 pm',
        carUrl: '/img/cars/nj_livingston_car.webp',
        mapUrl: '/img/maps/nj_livingston_map.webp',
        employees: [
            { id: 1, name: 'Aydin', image: '/img/employees/employee1.webp' },
            { id: 2, name: 'Oreck', image: '/img/employees/employee2.webp' },
            { id: 3, name: 'Farr', image: '/img/employees/employee3.webp' },
        ]
    },
}
