export * from './skeleton';
export * from './brands-select-skeleton';
export * from './slots-skeleton';
export * from './faqs-skeleton';
export * from './blogs-list-skeleton';
export * from './blog-info-skeleton';
export * from './locations-title-skeleton';
export * from './locations-service-title-skeleton';
export * from './brands-title-skeleton';
