name: Deploy

on:
  push:
    branches:
      - dev
      
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install SSH Key
        uses: webfactory/ssh-agent@v0.5.4
        with:
          ssh-private-key: ${{ secrets.DO_SSH_KEY }}

      - name: Copy Files to Server
        run: |
          rsync -avz -e "ssh -o StrictHostKeyChecking=no -o ServerAliveInterval=60 -o ServerAliveCountMax=5" ./UltraFix-Website-Next.js/ root@198.211.108.190:/var/www/ultrafix-web-front/

      - name: Install dependencies on Server
        run: |
          ssh -o StrictHostKeyChecking=no -o ServerAliveInterval=60 -o ServerAliveCountMax=5 root@198.211.108.190 << 'EOF'
            cd /var/www/ultrafix-web-front
            npm install
          EOF

      - name: Build Project on Server
        run: |
          ssh -o StrictHostKeyChecking=no -o ServerAliveInterval=60 -o ServerAliveCountMax=5 root@198.211.108.190 << 'EOF'
            cd /var/www/ultrafix-web-front
            npm run build
          EOF

      - name: Start or Restart Application using PM2
        run: |
          ssh -o StrictHostKeyChecking=no -o ServerAliveInterval=60 -o ServerAliveCountMax=5 root@198.211.108.190 << 'EOF'
            cd /var/www/ultrafix-web-front
            pm2 restart ultrafix-web-front || pm2 start npm --name "ultrafix-web-front" -- start
          EOF

      - name: Clean Up Build Cache
        run: |
          ssh -o StrictHostKeyChecking=no -o ServerAliveInterval=60 -o ServerAliveCountMax=5 root@198.211.108.190 << 'EOF'
            cd /var/www/ultrafix-web-front
            npm cache clean --force
          EOF
