name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install SSH Key
        uses: webfactory/ssh-agent@v0.5.4
        with:
          ssh-private-key: ${{ secrets.DO_SSH_KEY }}

      - name: Copy Files to Server
        run: |
          rsync -avz -e "ssh -o StrictHostKeyChecking=no" ./ root@137.184.157.106:/var/www/ultrafix-web-front/

      - name: Install dependencies on Server
        run: |
          ssh -o StrictHostKeyChecking=no root@137.184.157.106 << 'EOF'
            cd /var/www/ultrafix-web-front
            npm install
            npm run build
            pm2 restart ultrafix-web-front || pm2 start npm --name "ultrafix-web-front" -- start
          EOF
